_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

seed: 12345

min_epochs: 1
max_epochs: 10

weights_summary: null
progress_bar_refresh_rate: 10
check_val_every_n_epoch: 10

terminate_on_nan: True
fast_dev_run: False

checkpoint: null
weight_only: False

dense_volume: False
post_process: True