data_dir: ${data_dir}  # data_dir is specified in config.yaml

subdomain: "fusion"

name: "fusion_inference_dataset"
img_res: [480, 640]
train_cameras: False
num_pixels: 5000
scan_id: "scene3d/lounge"
num_images: 300
skip_images: 10
sample_shift: 0

downsample_scale: 1.
downsample_mode: null # or sparse
train_batch_size: 1
eval_batch_size: 1
max_eval_imgs: 1
shuffle: True
num_workers: 8
first_k: 2
max_neighbor_images: 5

out_root: null

# for end-to-end
depth_scale: 1000.