# specify here default training configuration
defaults:
    - trainer: default_trainer.yaml
    - model: default_model.yaml
    - optimizer: adam.yaml
    - dataset: default_dataset.yaml
    # - callbacks: default_callbacks.yaml  # set this to null if you don't want to use callbacks
    - loggers: null  # set logger here or use command line (e.g. `python run.py logger=wandb`)

    # enable color logging
    # - override hydra/hydra_logging: colorlog
    # - override hydra/job_logging: colorlog

disable_warnings: False
debug: False

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}
# path to folder with data
data_dir: ${work_dir}/data/

device_type: "cuda"

hydra:
    # output paths for hydra logs
    run:
        dir: logs/${hydra.job.name}/
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}

    job:
        # you can set here environment variables that are universal for all users
        # for system specific variables (like data paths) it's better to use .env file!
        env_set:
            # currently there are some issues with running sweeps alongside wandb
            # https://github.com/wandb/client/issues/1314
            # this env var fixes that
            WANDB_START_METHOD: thread